language: objective-c
osx_image: xcode7.2

branches:
  except:
    - gh-pages

install:
  - gem install xcpretty

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -project HTMLKit.xcodeproj -scheme HTMLKit-OSX -sdk macosx -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
- xcodebuild -project HTMLKit.xcodeproj -scheme HTMLKit-OSX -sdk macosx -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
- xcodebuild -project HTMLKit.xcodeproj -scheme HTMLKit-iOS -sdk iphonesimulator -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
- xcodebuild -project HTMLKit.xcodeproj -scheme HTMLKit-iOS -sdk iphonesimulator -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

