nguage: objective-c
osx_image: xcode7.2
script:
- xctool -project HTMLKit.xcodeproj -scheme HTMLKit-OSX -sdk macosx -configuration Release ONLY_ACTIVE_ARCH=NO
- xctool test -project HTMLKit.xcodeproj -scheme HTMLKitTests-OSX -sdk macosx ONLY_ACTIVE_ARCH=NO
- xctool -project HTMLKit.xcodeproj -scheme HTMLKit-iOS -sdk iphoneos -configuration Release ONLY_ACTIVE_ARCH=NO
- xctool test -project HTMLKit.xcodeproj -scheme HTMLKitTests-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

